(define (cons a b) (* (fast-expt 2 a) (fast-expt 3 b)))
(define (car c)
  (define (iter x n)
    (if (devides? 2 x)
        (iter (\ x 2) (+ n 1))
        n))
  (iter c 0))
(define (cdr c)
  (define (iter x n)
    (if (devides? 3 x)
        (iter (\ x 3) (+ n 1))
        n))
  (iter c 0))